In [1]:
import pickle
import numpy as np
import cv2

In [4]:
outeample = pickle.load(open("/Disk4/xudong/HAKE-Action-Torch-Activity2Vec/out/res/89.pkl", "rb"))
print(outeample.keys())

dict_keys(['human_bboxes', 'part_bboxes', 'keypoints', 'human_scores', 'skeletons', 'f_pasta', 'p_pasta', 'p_verb'])


In [5]:
# cap = cv2.VideoCapture("../DemoVideo/test.mp4")
# SCORE_THRES = 1.5
print(outeample['human_scores'])

tensor([[2.6741],
        [2.4466],
        [2.4528],
        [1.6826],
        [2.6800],
        [2.6440],
        [2.4294],
        [2.1880],
        [1.9360],
        [2.5297],
        [2.4050],
        [1.8320],
        [2.0687],
        [1.5873],
        [1.9584],
        [1.6710],
        [1.0040],
        [1.4340],
        [0.7103],
        [0.7373]])


In [69]:
total_frame = cap.get(7)
speed = cap.get(5)
print(total_frame, speed)

146.0 25.0


In [70]:
_, frame = cap.read()
print(frame.shape)

(720, 1280, 3)


In [71]:
# print(frame)
print(len(frame[0]))
print(len(frame))

1280
720


In [72]:
frame = cv2.GaussianBlur(frame, (5, 5), 1)

In [73]:
# print(outeample['human_bboxes'])
outeample_numpy = np.array(outeample['human_bboxes'])
# print(outeample_numpy)
center_slide = []
for per_human_box in outeample_numpy:
    x_min, y_min, x_max, y_max = per_human_box
    center_x = (int)(x_min + x_max) // 2
    center_y = (int)(y_min + y_max) // 2
    mid_point = [
        [center_y - 1, center_x - 1], [center_y - 1, center_x], [center_y - 1, center_x + 1],
        [center_y    , center_x - 1], [center_y    , center_x], [center_y    , center_x + 1],
        [center_y + 1, center_x - 1], [center_y + 1, center_x], [center_y + 1, center_x + 1]
    ]
    # print(mid_point)
    center_slide.append(mid_point)

In [74]:
print(len(center_slide))

18


In [75]:
# print(center_slide)

In [76]:
cv2.imwrite("out.jpg", frame)

True

In [77]:
print(len(frame))
print(len(frame[0]))

720
1280


In [78]:
color_pair = []
for mid_point in center_slide:
    color_list = []
    for coordinate in mid_point:
        color = frame[coordinate[0], coordinate[1]]
        color_list.append(color)
    # print(color_list)
    color_list = np.average(color_list, axis=0)
    # print(color_list)
    color_pair.append(color_list)

In [79]:
print(len(color_pair))
print(color_pair)

18
[array([57.        , 51.22222222, 52.77777778]), array([ 66.33333333, 165.77777778, 185.44444444]), array([115.77777778, 214.77777778, 229.44444444]), array([12.11111111, 44.77777778, 46.22222222]), array([51.44444444, 37.55555556, 37.77777778]), array([ 85.77777778, 121.88888889, 149.77777778]), array([102.22222222, 223.22222222, 228.55555556]), array([ 50.        , 165.88888889, 196.77777778]), array([28.77777778, 39.88888889, 40.44444444]), array([14.66666667, 40.55555556, 46.55555556]), array([21.77777778, 59.88888889, 56.44444444]), array([26.11111111, 46.44444444, 44.33333333]), array([ 97.22222222, 137.55555556, 166.66666667]), array([42.        , 45.55555556, 49.22222222]), array([ 87.33333333, 177.66666667, 208.88888889]), array([18.11111111, 54.33333333, 70.33333333]), array([ 62.88888889, 155.55555556, 181.22222222]), array([42.        , 82.77777778, 76.44444444])]


In [80]:
for idx in range(len(color_pair)):
    color_pair[idx] = color_pair[idx].tolist()
color_pair = np.array(color_pair)
print(color_pair)

[[ 57.          51.22222222  52.77777778]
 [ 66.33333333 165.77777778 185.44444444]
 [115.77777778 214.77777778 229.44444444]
 [ 12.11111111  44.77777778  46.22222222]
 [ 51.44444444  37.55555556  37.77777778]
 [ 85.77777778 121.88888889 149.77777778]
 [102.22222222 223.22222222 228.55555556]
 [ 50.         165.88888889 196.77777778]
 [ 28.77777778  39.88888889  40.44444444]
 [ 14.66666667  40.55555556  46.55555556]
 [ 21.77777778  59.88888889  56.44444444]
 [ 26.11111111  46.44444444  44.33333333]
 [ 97.22222222 137.55555556 166.66666667]
 [ 42.          45.55555556  49.22222222]
 [ 87.33333333 177.66666667 208.88888889]
 [ 18.11111111  54.33333333  70.33333333]
 [ 62.88888889 155.55555556 181.22222222]
 [ 42.          82.77777778  76.44444444]]


In [81]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.cluster import KMeans
#from sklearn import datasets
from sklearn.datasets import load_iris

In [82]:
# color_pair
# plt.scatter(color_pair[:, 0], color_pair[:, 1], c = "red", marker='o', label='see')
# plt.xlabel('petal length')
# plt.ylabel('petal width')
# plt.legend(loc=2)
# plt.show()

In [83]:
estimator = KMeans(n_clusters=2)
estimator.fit(color_pair)
label_pred = estimator.labels_ 

In [85]:
x0 = color_pair[label_pred == 0]
x1 = color_pair[label_pred == 1]
print(np.average(x0))
print(np.average(x1))
# print(x0)
# print(x1)

149.0277777777778
44.585185185185175


In [4]:
from box_utils import compute_IOU
rec1 = [0, 0, 1, 1]
rec2 = [0, 0, 2, 2]
print(compute_IOU(rec2, rec1))

0.25


In [6]:
import numpy as np
mask = np.ones(3)
print(mask)

[1. 1. 1.]


In [9]:
for i in range(5):
    for j in range(i + 1, 5):
        print(i, j)

0 1
0 2
0 3
0 4
1 2
1 3
1 4
2 3
2 4
3 4
